Repository OrdnanceSurvey/osbng-py, pull requests merged in 2025-07, with the labels that each got.

#17 Fix setuptools package discovery
  pyproject.toml
Labels: bug

#21 Add TypedDict test case classes and expected_warning handling to traversal tests
  tests/data/traversal_test_cases.json
  tests/test_traversal.py
Labels: documentation

#24 Require keyword-only arguments in some functions
  CITATION.cff
  osbng/__init__.py
  osbng/bng_reference.py
  osbng/hierarchy.py
  osbng/indexing.py
  osbng/traversal.py
  pyproject.toml
  tests/test_hierarchy.py
  tests/test_indexing.py
Labels: enhancement
